service: image-process

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "s3:GetObject"
       - "s3:PutObject"
       - "s3:PutObjectAcl"
      Resource: "*"

functions:
  resize:
    handler: resize.f
